PATRONES_INICIO = {
    "FACTURA_COMERCIAL": [
        "FACTURA COMERCIAL", "FACTURA", 
        "COMMERCIAL INVOICE", "INVOICE", 
        "HANDELSRECHNUNG", "RECHNUNG", 
        "FATURA COMERCIAL", "FATURA", 
        "HANDELSFACTUUR", "FACTUUR",
        "FACTURE COMMERCIALE", "FACTURE"
    ],
    
    "DOCUMENTO_TRANSPORTE": [
        "CONOCIMIENTO DE EMBARQUE", "GUÍA AÉREA", "CARTA DE PORTE",
        "BILL OF LADING", "B/L", "WAYBILL", "AIR WAYBILL", "ROAD WAYBILL", "SEA WAYBILL",
        "FRACHTBRIEF", "LUFTFRACHTBRIEF", 
        "CONHECIMENTO DE EMBARQUE", "CARTA DE PORTE", 
        "ZEEVRACHTBRIEF", "VRACHTBRIEF",
        "CONNAISSEMENT", "LETTRE DE TRANSPORT AÉRIEN", "LETTRE DE VOITURE"
    ],
    
    "CERTIFICADO_ORIGEN": [
        "CERTIFICADO DE ORIGEN",
        "CERTIFICATE OF ORIGIN", 
        "URSPRUNGSZEUGNIS",
        "CERTIFICADO DE ORIGEM", 
        "CERTIFICAAT VAN OORSPRONG",
        "CERTIFICAT D'ORIGINE"
    ],
    
    "LISTA_EMBALAJE": [
        "LISTA DE EMBALAJE", "LISTA DE EMPAQUE",
        "PACKING LIST", "PACKING LIST ORDER", 
        "PACKLISTE",
        "LISTA DE EMBALAGEM", 
        "PAKLIJST",
        "LISTE DE COLISAGE"
    ],
    
    "CERTIFICADO_SANITARIO_SAG": [
        "CERTIFICADO SANITARIO", "CERTIFICADO FITOSANITARIO", "CERTIFICADO DE ANÁLISIS", "CERTIFICADO ZOOSANITARIO", 
        "HEALTH CERTIFICATE", "PHYTOSANITARY CERTIFICATE", "CERTIFICATE OF ANALYSIS", "VETERINARY CERTIFICATE",
        "GESUNDHEITSZEUGNIS", "ANALYSEZERTIFIKAT",
        "CERTIFICADO SANITÁRIO", "CERTIFICADO DE ANÁLISE", 
        "GEZONDHEIDSCERTIFICAAT", "CERTIFICAAT VAN ANALYSE",
        "CERTIFICAT SANITAIRE", "CERTIFICAT D'ANALYSE"
    ],
    
    "POLIZA_SEGURO": [
        "PÓLIZA DE SEGURO", "CERTIFICADO DE SEGURO",
        "INSURANCE POLICY", "INSURANCE CERTIFICATE", "COVER NOTE",
        "VERSICHERUNGSPOLICE", "VERSICHERUNGSZERTIFIKAT",
        "APÓLICE DE SEGURO", "CERTIFICADO DE SEGURO",
        "VERZEKERINGSBEWIJS", "POLIS",
        "POLICE D'ASSURANCE", "CERTIFICAT D'ASSURANCE"
    ]
}

PATRON_DEFAULT = "UNKNOWN_DOCUMENT"